FROM node:14 as build-stage

ARG REACT_APP_CHAIN_ID
ARG REACT_APP_MSG_VERSION
ARG REACT_APP_NODE_URL
ARG REACT_APP_EXPLORER_URL

ENV REACT_APP_CHAIN_ID=${REACT_APP_CHAIN_ID:-333}
ENV REACT_APP_MSG_VERSION=${REACT_APP_MSG_VERSION:-1}
ENV REACT_APP_NODE_URL=${REACT_APP_NODE_URL:-https://dev-api.zilliqa.com}
ENV REACT_APP_EXPLORER_URL=${REACT_APP_EXPLORER_URL:-https://viewblock.io/zilliqa}

WORKDIR /app
COPY . ./
RUN yarn install
RUN yarn ci
RUN REACT_APP_CHAIN_ID=${REACT_APP_CHAIN_ID} REACT_APP_MSG_VERSION=${REACT_APP_MSG_VERSION} REACT_APP_NODE_URL=${REACT_APP_NODE_URL} REACT_APP_EXPLORER_URL=${REACT_APP_EXPLORER_URL} yarn build

FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]